(function(k,q,w,g){function e(b,a){try{return q.hasOwnProperty?b.hasOwnProperty(a.toString()):Object.prototype.hasOwnProperty.call(b,a.toString())}catch(d){}}function n(b){var a=b.css||"";this.setValues(b);this.span=k("<span/>").css({position:"relative",left:"-50%",top:"0","white-space":"nowrap"}).addClass(a);this.div=k("<div/>").css({position:"absolute",display:"none"});this.span.appendTo(this.div)}function s(b,a){e(q,"google")&&(this.markerCluster=this.map=null,this._markers=[],this._labels=[],
this.container=b,this.options=k.extend({},v,a),this.interval=parseInt(this.options.interval,10)||110,this.googleMapOptions={center:"",control:this.options.control,disableDoubleClickZoom:this.options.disableDoubleClickZoom,disableDefaultUI:this.options.disableDefaultUI,draggable:this.options.draggable,keyboardShortcuts:this.options.keyboardShortcuts,mapTypeId:google.maps.MapTypeId[this.options.mapTypeId.toUpperCase()],mapTypeControl:this.options.mapTypeControl,mapTypeControlOptions:{position:google.maps.ControlPosition[this.options.mapTypeControlOptions.position],
style:google.maps.MapTypeControlStyle[this.options.mapTypeControlOptions.style.toUpperCase()]},maxZoom:this.options.maxZoom,minZoom:this.options.minZoom,navigationControl:this.options.navigationControl,navigationControlOptions:{position:google.maps.ControlPosition[this.options.navigationControlOptions.position],style:google.maps.NavigationControlStyle[this.options.navigationControlOptions.style.toUpperCase()]},panControl:this.options.panControl,panControlOptions:{position:google.maps.ControlPosition[this.options.panControlOptions.position]},
rotateControl:this.options.rotateControl,scaleControl:this.options.scaleControl,scaleControlOptions:{position:google.maps.ControlPosition[this.options.scaleControlOptions.position],style:google.maps.ScaleControlStyle[this.options.scaleControlOptions.style.toUpperCase()]},scrollwheel:this.options.scrollwheel,streetViewControl:this.options.streetViewControl,streetViewControlOptions:{position:google.maps.ControlPosition[this.options.streetViewControlOptions.position]},zoom:this.options.zoom,zoomControl:this.options.zoomControl,
zoomControlOptions:{position:google.maps.ControlPosition[this.options.zoomControlOptions.position],style:google.maps.ZoomControlStyle[this.options.zoomControlOptions.style.toUpperCase()]}},"[object Array]"===Object.prototype.toString.call(this.options.center)?2===this.options.center.length&&(this.googleMapOptions.center=new google.maps.LatLng(this.options.center[0],this.options.center[1])):e(this.options.center,"x")&&e(this.options.center,"y")?this.googleMapOptions.center=new google.maps.LatLng(this.options.center.x,
this.options.center.y):e(this.options.center,"lat")&&e(this.options.center,"lng")&&(this.googleMapOptions.center=new google.maps.LatLng(this.options.center.lat,this.options.center.lng)),!0===this.options.disableDefaultUI&&(this.googleMapOptions.mapTypeControl=!1,this.googleMapOptions.navigationControl=!1,this.googleMapOptions.panControl=!1,this.googleMapOptions.rotateControl=!1,this.googleMapOptions.scaleControl=!1,this.googleMapOptions.streetViewControl=!1,this.googleMapOptions.zoomControl=!1),e(this.options,
"styles")&&("string"===typeof this.options.styles?e(r,this.options.styles)&&(this.googleMapOptions.styles=r[this.options.styles]):"[object Array]"===Object.prototype.toString.call(this.options.styles)&&(this.googleMapOptions.styles=this.options.styles)),k(this.container).html(this.options.loading),this.init())}var v={center:{x:"",y:""},control:!0,disableDoubleClickZoom:!1,disableDefaultUI:!1,draggable:!0,infoWindowAutoClose:!0,keyboardShortcuts:!0,mapTypeControl:!0,mapTypeControlOptions:{position:"TOP_RIGHT",
style:"DEFAULT"},mapTypeId:"ROADMAP",marker:[],markerFitBounds:!1,markerCluster:!1,maxZoom:null,minZoom:null,panControl:!0,panControlOptions:{position:"LEFT_TOP"},polyline:[],navigationControl:!0,navigationControlOptions:{position:"TOP_LEFT",style:"DEFAULT"},scaleControl:!0,scaleControlOptions:{position:"BOTTOM_LEFT",style:"DEFAULT"},scrollwheel:!0,streetViewControl:!0,streetViewControlOptions:{position:"LEFT_TOP"},zoom:4,zoomControl:!0,zoomControlOptions:{style:"LARGE",position:"LEFT_TOP"},notfound:"\u627e\u4e0d\u5230\u67e5\u8a62\u7684\u5730\u9ede",
loading:"\u8b80\u53d6\u4e2d&hellip;",kml:{url:"",viewport:!0,infowindow:!1},interval:200,event:null,showStreetView:!1,autoLocation:!1},t=0,u=0,r={},r={greyscale:[{featureType:"all",stylers:[{saturation:-100},{gamma:.5}]}]};n.prototype=new google.maps.OverlayView;n.prototype.onAdd=function(){var b=this.getPanes().overlayLayer;this.div.appendTo(k(b));this.listeners=[google.maps.event.addListener(this,"visible_changed",this.onRemove)]};n.prototype.draw=function(){var b=this.getProjection(),a={};try{a=
b.fromLatLngToDivPixel(this.get("position")),this.div.css({left:a.x+"px",top:a.y+"px",display:"block"}),this.text&&this.span.html(this.text.toString())}catch(d){}};n.prototype.onRemove=function(){k(this.div).remove()};s.prototype={VERSION:"2.8.8",_polylines:[],_polygons:[],_circles:[],_kmls:[],_directions:[],bounds:new google.maps.LatLngBounds,setZoom:function(b,a){e(a,"zoom")&&b&&b.setZoom(a.zoom)},kml:function(b,a){var d={},c="",d={};a=a?a:this.options;g!==a.kml&&(d={preserveViewport:!0,suppressInfoWindows:!1},
c="string"===typeof a.kml&&0!==a.kml.length?a.kml:g!==a.kml.url?a.kml.url:"",d=new google.maps.KmlLayer(c,k.extend(d,a.kml)),this._kmls.push(d),d.setMap(b))},direction:function(b,a){var d="";a=a?a:this.options;if(g!==a.direction&&0<a.direction.length)for(d in a.direction)e(a.direction,d)&&g!==a.direction[d]&&this.directionService(a.direction[d])},markers:function(b,a,d){var c="",f=0,h=0,l=[],m=[];a=a?a:this.options;u=t=0;l=this._markers;if((!d||0===l.length)&&g!==a.marker&&0<a.marker.length)for(c in a.marker)e(a.marker,
c)&&e(a.marker[c],"addr")&&("object"===typeof a.marker[c].addr&&2===a.marker[c].addr.length?this.markerDirect(b,a.marker[c],a):"string"===typeof a.marker[c].addr&&this.markerByGeocoder(b,a.marker[c],a));if("modify"===d)for(m=this._labels,f=0;f<a.marker.length;f+=1)if(g!==a.marker[f].id){for(h=0;h<l.length;h+=1)a.marker[f].id===l[h].id&&g!==a.marker[f].addr&&(l[h].setPosition(new google.maps.LatLng(a.marker[f].addr[0],a.marker[f].addr[1])),"function"===typeof l[f].infoWindow.setContent&&l[h].infoWindow.setContent(a.marker[f].text));
for(h=0;h<m.length;h+=1)a.marker[f].id===m[h].id&&(e(a.marker[f],"label")&&(m[h].text=a.marker[f].label),m[h].draw())}else"object"===typeof a.marker[f].addr&&2===a.marker[f].addr.length?this.markerDirect(b,a.marker[f]):"string"===typeof a.marker[f].addr&&this.markerByGeocoder(b,a.marker[f]);if(e(a,"markerCluster")&&!0===a.markerCluster&&"function"===typeof MarkerClusterer)return new MarkerClusterer(b,this._markers)},drawPolyline:function(b,a){var d={},c=0,f="",h={},l=0,m=new google.maps.MVCArray,
k=[],h={},p=[],n={};a=a?a:this.options;if(g!==a.polyline&&g!==a.polyline.coords){for(f in a.polyline.coords)e(a.polyline.coords,f)&&(h=a.polyline.coords,g!==h[f]&&m.push(new google.maps.LatLng(h[f][0],h[f][1])));d=new google.maps.Polyline({strokeColor:a.polyline.color||"#FF0000",strokeOpacity:1,strokeWeight:a.polyline.width||2});this._polylines.push(d);2<m.getLength()&&m.forEach(function(a,b){0<b&&m.getLength()-1>b&&p.push({location:a,stopover:!1})});!0===a.polyline.snap?(h=new google.maps.DirectionsService,
h.route({origin:m.getAt(0),waypoints:p,destination:m.getAt(m.getLength()-1),travelMode:google.maps.DirectionsTravelMode.DRIVING},function(b,f){if(f===google.maps.DirectionsStatus.OK){c=0;for(l=b.routes[0].overview_path.length;c<l;c+=1)k.push(b.routes[0].overview_path[c]);d.setPath(k);"function"===typeof a.polyline.getDistance&&(n=b.routes[0].legs[0].distance,a.polyline.getDistance.call(this,n))}})):(d.setPath(m),e(google.maps.geometry,"spherical")&&"function"===typeof google.maps.geometry.spherical.computeDistanceBetween&&
(n=google.maps.geometry.spherical.computeDistanceBetween(m.getAt(0),m.getAt(m.getLength()-1)),"function"===typeof a.polyline.getDistance&&a.polyline.getDistance.call(this,n)));d.setMap(b)}},drawPolygon:function(b,a){var d={},d="",c={},f=[];a=a?a:this.options;if(g!==a.polygon&&g!==a.polygon.coords){for(d in a.polygon.coords)e(a.polygon.coords,d)&&(c=a.polygon.coords,g!==c[d]&&f.push(new google.maps.LatLng(c[d][0],c[d][1])));d=new google.maps.Polygon({path:f,strokeColor:a.polygon.color||"#FF0000",strokeOpacity:1,
strokeWeight:a.polygon.width||2,fillColor:a.polygon.fillcolor||"#CC0000",fillOpacity:.35});this._polygons.push(d);d.setMap(this.map);k.isFunction(a.polygon.click)&&google.maps.event.addListener(d,"click",a.polygon.click)}},drawCircle:function(b,a){var d=0,c={},c={};a=a?a:this.options;if(g!==a.circle&&0<a.circle.length)for(d=a.circle.length-1;0<=d;d-=1)c=a.circle[d],g!==c.center.x&&g!==c.center.y&&(c=new google.maps.Circle({strokeColor:c.color||"#FF0000",strokeOpacity:c.opacity||.8,strokeWeight:c.width||
2,fillColor:c.fillcolor||"#FF0000",fillOpacity:c.fillopacity||.35,map:this.map,center:new google.maps.LatLng(c.center.x,c.center.y),radius:c.radius||10,zIndex:100,id:e(a,"id")?a.id:""}),this._circles.push(c),k.isFunction(a.circle[d].click)&&google.maps.event.addListener(c,"click",a.circle[d].click))},overlay:function(){var b=this.map,a=this.options;try{this.kml(b,a),this.direction(b,a),this.markers(b,a),this.drawPolyline(b,a),this.drawPolygon(b,a),this.drawCircle(b,a),this.streetView(b,a),this.geoLocation(b,
a)}catch(d){console.dir(d)}},markerIcon:function(b){var a={};if(e(b,"icon")){if("string"===typeof b.icon)return b.icon;e(b.icon,"url")&&(a.url=b.icon.url);e(b.icon,"size")&&g!==b.icon.size[0]&&g!==b.icon.size[1]&&(a.scaledSize=new google.maps.Size(b.icon.size[0],b.icon.size[1]));e(b.icon,"anchor")&&g!==b.icon.anchor[0]&&g!==b.icon.anchor[1]&&(a.anchor=new google.maps.Point(b.icon.anchor[0],b.icon.anchor[1]))}return a},markerDirect:function(b,a){var d={},c={},c={},c=e(a,"id")?a.id:"",d=e(a,"title")?
a.title.toString().replace(/<([^>]+)>/g,""):!1,f=e(a,"text")?a.text.toString():!1,h={map:b,position:new google.maps.LatLng(a.addr[0],a.addr[1]),animation:null,id:c},l=this.markerIcon(a);d&&(h.title=d);f&&(h.text=f,h.infoWindow=new google.maps.InfoWindow({content:f}));if("string"===typeof l||e(l,"url"))h.icon=l;e(a.animation)&&"string"===typeof a.animation&&(h.animation=google.maps.Animation[a.animation.toUpperCase()]);d=new google.maps.Marker(h);this._markers.push(d);e(d,"position")&&(d.getPosition().lat()&&
d.getPosition().lng()&&this.bounds.extend(d.position),!0===this.options.markerFitBounds&&this._markers.length===this.options.marker.length&&b.fitBounds(this.bounds));!0===this.options.markerCluster&&"function"===typeof MarkerClusterer&&t===this.options.marker.length?this.markerCluster=new MarkerClusterer(b,this._markers):(c={map:b,css:g!==a.css?a.css:"",id:c},"string"===typeof a.label&&0!==a.label.length&&(c.text=a.label,c=new n(c),c.bindTo("position",d,"position"),c.bindTo("text",d,"position"),c.bindTo("visible",
d),this._labels.push(c)),this.bindEvents(d,a.event))},markerByGeocoder:function(b,a){var d=new google.maps.Geocoder,c=this;e(a,"addr")&&(-1!==a.addr.indexOf(",")&&(a.addr="loc: "+a.addr),d.geocode({address:a.addr},function(d,h){if(h===google.maps.GeocoderStatus.OVER_QUERY_LIMIT)q.setTimeout(function(){c.markerByGeocoder(b,a)},100);else if(h===google.maps.GeocoderStatus.OK){var l={},g={},g={},k=e(a,"id")?a.id:"",l=e(a,"title")?a.title.toString().replace(/<([^>]+)>/g,""):!1,g=e(a,"text")?a.text.toString():
!1,k={map:b,position:d[0].geometry.location,animation:null,id:k},p=c.markerIcon(a);l&&(k.title=l);g&&(k.text=g,k.infoWindow=new google.maps.InfoWindow({content:g}));if("string"===typeof p||e(p,"url"))k.icon=p;e(a,"animation")&&"string"===typeof a.animation&&(k.animation=google.maps.Animation[a.animation.toUpperCase()]);l=new google.maps.Marker(k);c._markers.push(l);e(l,"position")&&l.getPosition().lat()&&l.getPosition().lng()&&c.bounds.extend(k.position);!0===c.options.markerFitBounds&&c._markers.length===
c.options.marker.length&&b.fitBounds(c.bounds);e(c.options,"markerCluster")&&"function"===typeof MarkerClusterer&&u===c.options.marker.length?c.markerCluster=new MarkerClusterer(b,c._markers):(g={map:c.map,css:a.css||""},"string"===typeof a.label&&0!==a.label.length&&(g.text=a.label,g=new n(g),g.bindTo("position",l,"position"),g.bindTo("text",l,"position"),g.bindTo("visible",l),c._labels.push(g)),c.bindEvents(l,a.event))}}))},directionService:function(b){var a=[],d=new google.maps.DirectionsService,
c=new google.maps.DirectionsRenderer,f={travelMode:google.maps.DirectionsTravelMode.DRIVING,optimizeWaypoints:b.optimize||!1},h={},e=0,m=0;"string"===typeof b.from&&(f.origin=b.from);"string"===typeof b.to&&(f.destination=b.to);"string"===typeof b.travel&&b.travel.length&&(f.travelMode=google.maps.TravelMode[b.travel.toUpperCase()]);h=k(g!==b.panel?b.panel:null);if(g!==b.waypoint&&0!==b.waypoint){e=0;for(m=b.waypoint.length;e<m;e+=1)a.push({location:b.waypoint[e].toString(),stopover:!0});f.waypoints=
a}g!==f.origin&&g!==f.destination&&(d.route(f,function(a,d){d===google.maps.DirectionsStatus.OK&&(g!==b.autoViewport&&c.setOptions({preserveViewport:!1===b.autoViewport?!0:!1}),c.setDirections(a))}),c.setMap(this.map),h.length&&c.setPanel(h.get(0)),this._directions.push(c))},bindEvents:function(b,a){var d=this,c={};switch(typeof a){case "function":google.maps.event.addListener(b,"click",a);break;case "object":for(c in a)"function"===typeof a[c]?google.maps.event.addListener(b,c,a[c]):e(a[c],"func")&&
"function"===typeof a[c].func?e(a[c],"once")&&!0===a[c].once?google.maps.event.addListenerOnce(b,c,a[c].func):google.maps.event.addListener(b,c,a[c].func):"function"===typeof a[c]&&google.maps.event.addListener(b,c,a[c])}e(b,"infoWindow")&&google.maps.event.addListener(b,"click",function(){var a=0,c={};if(!0===d.options.infoWindowAutoClose)for(a=0;a<d._markers.length;a+=1)c=d._markers[a],g!==c.infoWindow&&"function"===typeof c.infoWindow.close&&c.infoWindow.close();b.infoWindow.open(d.map,b)})},streetView:function(b,
a){var d=b.getStreetView();d.setPosition(b.getCenter());e(a,"showStreetView")&&d.setVisible(a.showStreetView)},panto:function(b){var a="",d={},c=this.map;e(this,"map")&&null!==c&&g!==c&&("string"===typeof b?(-1!==b.indexOf(",")&&(a="loc: "+b),d=new google.maps.Geocoder,d.geocode({address:b},function(a,b){b===google.maps.GeocoderStatus.OK&&k.isFunction(c.panTo)&&g!==a[0]&&c.panTo(a[0].geometry.location)})):("[object Array]"===Object.prototype.toString.call(b)?2===b.length&&(a=new google.maps.LatLng(b[0],
b[1])):e(b,"lat")&&e(b,"lng")?a=new google.maps.LatLng(b.lat,b.lng):e(b,"x")&&e(b,"y")&&(a=new google.maps.LatLng(b.x,b.y)),k.isFunction(c.panTo)&&g!==a&&c.panTo(a)))},clear:function(b){for(var a=[],d="",c=0,f=0,a="string"===typeof b?b.split(","):"[object Array]"===Object.prototype.toString.call(b)?b:[],a=a.length?a:"marker circle polygon polyline direction kml".split(" "),c=0;c<a.length;c+=1)if(d="_"+k.trim(a[c].toString().toLowerCase())+"s",g!==this[d]&&this[d].length){for(f=0;f<this[d].length;f+=
1)this.map===this[d][f].getMap()&&(this[d][f].set("visible",!1),this[d][f].set("directions",null),this[d][f].setMap(null));this[d].length=0}},modify:function(b){var a=[],d=[["kml","kml"],["marker","markers"],["direction","direction"],["polyline","drawPolyline"],["polygon","drawPolygon"],["circle","drawCircle"],["zoom","setZoom"],["showStreetView","streetView"]],c=0,f=this.map;if(g!==b){for(c=0;c<d.length;c+=1)e(b,d[c][0])&&a.push(d[c][1]);if(null!==f)if(a.length)for(c=0;c<a.length;c+=1){if("function"===
typeof this[a[c]])this[a[c]](f,b,"modify")}else e(b,"styles")&&(console.dir(b),"string"===typeof b.styles&&(b.styles=r[b.styles])),f.setOptions(b)}},geoLocation:function(b,a){var d={maximumAge:6E5,timeout:3E3,enableHighAccuracy:!1},c=navigator.geolocation;c&&!0===a.autoLocation&&c.getCurrentPosition(function(a){a&&b.panTo(new google.maps.LatLng(a.coords.latitude,a.coords.longitude))},function(a){},d)},init:function(){var b=this,a={};"string"===typeof b.options.center?q.setTimeout(function(){var d=
k(b.container),c="";-1!==b.options.center.indexOf(",")&&(b.options.center="loc: "+b.options.center);a=new google.maps.Geocoder;a.geocode({address:b.options.center},function(a,e){try{e===google.maps.GeocoderStatus.OVER_QUERY_LIMIT?b.init():e===google.maps.GeocoderStatus.OK&&0!==a.length?(b.googleMapOptions.center=e===google.maps.GeocoderStatus.OK&&0!==a.length?a[0].geometry.location:"",b.map=new google.maps.Map(b.container,b.googleMapOptions),google.maps.event.addListenerOnce(b.map,"idle",function(){b.overlay()}),
b.bindEvents(b.map,b.options.event)):(c=b.options.notfound.text||e,d.html(c.replace(/</g,"&lt;").replace(/>/g,"&gt;")))}catch(k){d.html((g!==k.message?k.message:k.description).toString())}})},b.interval):(b.map=new google.maps.Map(b.container,b.googleMapOptions),google.maps.event.addListenerOnce(b.map,"idle",function(){b.overlay()}),b.bindEvents(b.map,b.options.event))}};k.fn.tinyMap=function(b){var a=arguments,d=[],c={};return"string"===typeof b?(this.each(function(){c=k.data(this,"tinyMap");c instanceof
s&&"function"===typeof c[b]&&(d=c[b].apply(c,Array.prototype.slice.call(a,1)))}),g!==d?d:this):this.each(function(){k.data(this,"tinyMap")||k.data(this,"tinyMap",new s(this,b))})}})(jQuery,window,document);
